version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    networks:
      - mydockernet
    volumes:
      - db:/var/lib/mysql
  appserver:
    container_name: appserver
    env_file: ./.env
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - mydockernet
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
      - NODE_PORT=$NODE_DOCKER_PORT
      - JWT_EXPIRES_IN=100
      - JWT_SECRET=secret
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
  adminer:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: mysqldb
    ports:
      - 8080:8080
    networks:
      - mydockernet
  appclient:
    container_name: appclient
    build:
      context: ./react-antd-admin
      dockerfile: Dockerfile
    ports:
      - 9999:9999
    networks:
      - mydockernet
    environment:
      - REACT_APP_ENV=development
      - REACT_APP_API_URL=http://localhost:3000
    stdin_open: true
    depends_on:
      - appserver
    volumes:
      - ./react-antd-admin:/usr/src/app
      - /usr/src/app/node_modules
networks:
  mydockernet:
    driver: bridge
volumes:
  db: